'use client'

export { default as useBaseModal } from './hooks/useBaseModal'
export { RenderMode } from './hooks/useBaseModal'
export type { AcceptableElement, ModalEntry } from './hooks/useBaseModal'
export { default as useStaticModal } from './hooks/useStaticModal'
export { default as useDynamicModal } from './hooks/useDynamicModal'
export { default as BaseModalRenderer } from './components/BaseModalRenderer'
export type { BaseModalRendererProps } from './components/BaseModalRenderer'
export type { UseStaticModalReturn, ShowModalFn, CloseModalFn, UpdateModalContentFn } from './hooks/useStaticModal'
export type { UseDynamicModalReturn, RenderModalElementFn, ShowDynamicModalFn, CloseDynamicModalFn, FocusDynamicModalFn } from './hooks/useDynamicModal'
