'use client'

export { default as useBaseModal } from './hooks/useBaseModal'
export { default as storeBaseModal } from './store/modal'
export { RenderMode } from './types/modal'
export type { AcceptableElement, ModalEntry } from './types/modal'
export { default as useStaticModal } from './hooks/useStaticModal'
export { default as useDynamicModal } from './hooks/useDynamicModal'
export { default as BaseModalRenderer } from './components/BaseModalRenderer'
export type { BaseModalRendererProps } from './components/BaseModalRenderer'
export { default as ModalBackdrop } from './components/ModalBackdrop'
export type { ModalBackdropProps } from './components/ModalBackdrop'
export { default as ModalWindow } from './components/ModalWindow'
export type { ModalWindowProps } from './components/ModalWindow'
export { stopPropagation } from './utils/utils'
export type { UseStaticModalReturn, ShowModalFn, CloseModalFn, UpdateModalContentFn } from './hooks/useStaticModal'
export type { UseDynamicModalReturn, RenderModalElementFn, ShowDynamicModalFn, CloseDynamicModalFn, FocusDynamicModalFn } from './hooks/useDynamicModal'
